# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0010_trained_coding_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedcoding',
            name='location_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
