# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0009_usercoding_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedCategoryRelevance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsarticles.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TrainedCoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('model_info', models.TextField()),
                ('relevance', models.FloatField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsarticles.Article')),
                ('categories', models.ManyToManyField(through='newsarticles.TrainedCategoryRelevance', to='newsarticles.Category')),
            ],
        ),
        migrations.AddField(
            model_name='trainedcategoryrelevance',
            name='coding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsarticles.TrainedCoding'),
        ),
    ]
