# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0011_trainedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedlocation',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedlocation',
            name='neighborhood',
            field=models.TextField(blank=True, default=''),
        ),
    ]
