# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0012_trainedlocation_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoding',
            name='sentiment',
            field=models.IntegerField(blank=True, choices=[(1, 'Positive'), (0, 'Neutral'), (-1, 'Negative')], null=True),
        ),
    ]
