# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0013_usercoding_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedcoding',
            name='sentiment',
            field=models.FloatField(null=True),
        ),
    ]
