# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0014_trainedcoding_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedlocation',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercoding',
            name='sentiment',
            field=models.IntegerField(blank=True, choices=[(None, 'Not coded'), (1, 'Positive'), (0, 'Neutral'), (-1, 'Negative')], null=True),
        ),
    ]
