# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-14 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0017_auto_20191210_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedcoding',
            name='sentiment_processed',
            field=models.BooleanField(default=False),
        ),
    ]
