# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0018_trainedcoding_sentiment_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentCallsCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remaining_calls', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
