# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2023-11-26 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0019_sentimentcallscounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoding',
            name='offend_age',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='offend_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='offend_race',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='offend_sex',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='offend_weap',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='vict_age',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='vict_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='vict_race',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='vict_sex',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
