# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0020_add_trait_fields_to_user_coding'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoding',
            name='offend_ethnicity',
            field=models.CharField(choices=[(None, ''), ('HISPA', 'Hispanic or Latino'), ('NOHIS', 'Not Hispanic or Latino'), ('UND', 'Undetermined')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usercoding',
            name='vict_ethnicity',
            field=models.CharField(choices=[(None, ''), ('HISPA', 'Hispanic or Latino'), ('NOHIS', 'Not Hispanic or Latino'), ('UND', 'Undetermined')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usercoding',
            name='offend_race',
            field=models.CharField(choices=[(None, ''), ('WHI', 'White'), ('BAA', 'Black or African American'), ('AIAN', 'American Indian or Alaska Native'), ('ASIA', 'Asian'), ('NHPI', 'Native Hawaiian or Other Pacific Islander'), ('OTH', 'Other'), ('UND', 'Undetermined')], default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='usercoding',
            name='offend_sex',
            field=models.CharField(choices=[(None, ''), ('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANM', 'Transgender Male'), ('TRANF', 'Transgender Female'), ('UND', 'Undetermined')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='usercoding',
            name='offend_weap',
            field=models.CharField(choices=[(None, ''), ('FIRE', 'Firearms (handguns, rifles, shotguns)'), ('KNIF', 'Knives/cutting instruments'), ('OTH', 'Other weapon'), ('PERS', 'Personal weapons'), ('ARM', 'Strong-arm (hands/fists/other)'), ('UND', 'Undetermined')], default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='usercoding',
            name='vict_race',
            field=models.CharField(choices=[(None, ''), ('WHI', 'White'), ('BAA', 'Black or African American'), ('AIAN', 'American Indian or Alaska Native'), ('ASIA', 'Asian'), ('NHPI', 'Native Hawaiian or Other Pacific Islander'), ('OTH', 'Other'), ('UND', 'Undetermined')], default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='usercoding',
            name='vict_sex',
            field=models.CharField(choices=[(None, ''), ('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANM', 'Transgender Male'), ('TRANF', 'Transgender Female'), ('UND', 'Undetermined')], default=None, max_length=32),
        ),
    ]
