# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-07-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticles', '0021_add_dropdowns_to_user_coding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoding',
            name='offend_age',
        ),
        migrations.AddField(
            model_name='usercoding',
            name='offend_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='usercoding',
            name='vict_age',
        ),
        migrations.AddField(
            model_name='usercoding',
            name='vict_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
